# Generated by Django 4.1.4 on 2023-07-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('title', models.CharField(blank=True, default='Professor', max_length=20, null=True)),
                ('is_department_head', models.BooleanField(blank=True, default=False, null=True)),
                ('credits', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
