# Generated by Django 4.1.4 on 2023-05-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
