# Generated by Django 4.1.4 on 2023-07-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_requests', to='request.requestitem')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('code', models.CharField(max_length=5)),
                ('credits', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('prerequisite', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('corequisite', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='request.requestitem')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('chair', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.professor')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to='request.requestitem')),
            ],
        ),
        migrations.CreateModel(
            name='StartEndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_end_time_requests', to='request.requestitem')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('allocation_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='claim.allocationgroup')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_block_requests', to='request.requestitem')),
                ('start_end_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='claim.startendtime')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='claim.department')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_requests', to='request.requestitem')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_course', models.CharField(max_length=10)),
                ('number', models.CharField(blank=True, max_length=5)),
                ('campus', models.CharField(max_length=20)),
                ('soft_cap', models.IntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='claim.course')),
                ('primary_professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='authentication.professor')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_requests', to='request.requestitem')),
                ('term', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='claim.term')),
            ],
            options={
                'unique_together': {('course', 'term', 'number', 'request')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('classification', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], max_length=20)),
                ('capacity', models.IntegerField(blank=True, default=False, null=True)),
                ('is_general_purpose', models.BooleanField(blank=True, default=False, null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='claim.building')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', to='request.requestitem')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('style_code', models.CharField(blank=True, default='LEC', max_length=20, null=True)),
                ('style_description', models.CharField(blank=True, default='Lecture', max_length=20, null=True)),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='authentication.professor')),
                ('request', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='request.requestitem')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='claim.room')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='claim.section')),
                ('time_block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='claim.timeblock')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classrooms', models.IntegerField()),
                ('allocation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_allocations', to='claim.allocationgroup')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_allocations', to='claim.department')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='claim.subject'),
        ),
    ]
