# Generated by Django 4.1.4 on 2023-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_sharable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
