# Generated by Django 4.1.4 on 2023-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
