# Generated by Django 4.1.4 on 2023-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
