# Generated by Django 4.1.4 on 2023-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_alter_course_banner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='allocation_group',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='allocation_groups',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='time_blocks', to='claim.allocationgroup'),
        ),
    ]
