# Generated by Django 4.1.4 on 2023-05-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('claim', '0002_alter_timeblock_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='request',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to='request.requestitem'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='claim.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='claim.term'),
        ),
    ]
