# Generated by Django 4.1.4 on 2023-06-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_term_alter_meeting_request_alter_meeting_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classrooms', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_groups', to='claim.department')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentTimeBlockAllocation',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='allocation_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='claim.allocationgroup'),
        ),
    ]
