# Generated by Django 5.0 on 2024-01-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_alter_term_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='claim.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='claim.section'),
            preserve_default=False,
        ),
    ]
