# Generated by Django 4.1.4 on 2023-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_remove_timeblock_allocation_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='allocation_groups',
            field=models.ManyToManyField(blank=True, default=None, related_name='time_blocks', to='claim.allocationgroup'),
        ),
    ]
