# Generated by Django 5.0 on 2024-02-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('claim', '0004_alter_course_subject_alter_meeting_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='claim.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.department')),
                ('claim_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.subject')),
                ('claim_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.term')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='authentication.professor')),
            ],
        ),
        migrations.CreateModel(
            name='TimeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_exclusions', to='claim.preferences')),
            ],
        ),
    ]
