# Generated by Django 4.1.4 on 2023-06-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_allocationgroup_delete_departmenttimeblockallocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationgroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='allocationgroup',
            name='number_of_classrooms',
        ),
        migrations.CreateModel(
            name='DepartmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classrooms', models.IntegerField()),
                ('allocation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_allocations', to='claim.allocationgroup')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_allocations', to='claim.department')),
            ],
        ),
    ]
