# Generated by Django 4.1.4 on 2023-06-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_remove_allocationgroup_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='campus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='claim.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'term', 'number')},
        ),
    ]
