# Generated by Django 5.0 on 2024-02-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_alter_subject_department_preferences_timeexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.course')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_courses', to='claim.preferences')),
            ],
        ),
    ]
