# Generated by Django 4.1.4 on 2023-06-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
        ('authentication', '0002_alter_professor_email'),
        ('claim', '0006_alter_section_campus_alter_section_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='primary_professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='authentication.professor'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'term', 'number', 'request')},
        ),
    ]
