# Generated by Django 4.2.4 on 2024-03-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_alter_preferencescourse_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencescourse',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='claim.department'),
        ),
    ]
