# Generated by Django 4.1.4 on 2023-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_room_is_general_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
    ]
