# Generated by Django 4.2.4 on 2024-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_meeting_building_meeting_room_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room_is_general_purpose',
            field=models.CharField(blank=True, choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], max_length=20, null=True),
        ),
    ]
