# Generated by Django 4.1.4 on 2023-08-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0003_alter_term_options'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequestBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_request_bundles', to='authentication.professor')),
            ],
        ),
        migrations.CreateModel(
            name='EditSectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sections', to='request.editrequestbundle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sections', to='claim.section')),
            ],
        ),
        migrations.CreateModel(
            name='EditMeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to='claim.building')),
                ('edit_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_meetings', to='request.editsectionrequest')),
                ('original', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_meetings', to='claim.meeting')),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests_involving', to='authentication.professor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to='claim.room')),
            ],
        ),
        migrations.CreateModel(
            name='EditMeetingMessageBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('revised_accepted', 'Revised and Accepted'), ('denied', 'Denied')], max_length=20)),
                ('recipient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_bundles', to='authentication.professor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bundles', to='authentication.professor')),
            ],
        ),
        migrations.CreateModel(
            name='EditMeetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_changed', models.BooleanField()),
                ('old_start_time', models.TimeField(blank=True, null=True)),
                ('old_end_time', models.TimeField(blank=True, null=True)),
                ('old_day', models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2, null=True)),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('new_day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=2)),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='request.editmeetingmessagebundle')),
                ('new_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_new', to='claim.building')),
                ('new_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_new', to='authentication.professor')),
                ('new_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_new', to='claim.room')),
                ('old_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_old', to='claim.building')),
                ('old_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_old', to='authentication.professor')),
                ('old_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_of_old', to='claim.room')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='request.editmeetingrequest')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='claim.section')),
            ],
        ),
    ]
