# Generated by Django 4.1.4 on 2023-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_item_groups', to='authentication.professor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('changed', 'Changed'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='not_requested', max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='request.requestitemgroup')),
            ],
        ),
    ]
