# Generated by Django 4.1.4 on 2023-08-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editmeetingmessagebundle',
            options={'ordering': ['date_sent']},
        ),
    ]
