# Generated by Django 4.1.4 on 2023-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_remove_editsectionrequest_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editmeetingmessagebundle',
            options={'ordering': ['-date_sent']},
        ),
        migrations.AddField(
            model_name='editmeetingrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
