# Generated by Django 4.1.4 on 2023-09-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_editmeetingmessagebundle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmeetingmessage',
            name='request',
        ),
        migrations.AddField(
            model_name='editmeetingmessagebundle',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_bundles', to='request.editrequestbundle'),
        ),
    ]
