# Generated by Django 4.1.4 on 2023-09-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_alter_term_options'),
        ('request', '0007_alter_editsectionrequest_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsectionrequest',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_section', to='claim.section'),
        ),
    ]
