# Generated by Django 5.0 on 2024-01-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_remove_editmeetingmessagebundle_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editmeetingmessagebundlerequest',
            options={},
        ),
        migrations.RenameField(
            model_name='editmeetingmessagebundleresponse',
            old_name='section_bundle',
            new_name='request_bundle',
        ),
        migrations.AlterField(
            model_name='editmeetingmessagebundlerequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_message', to='request.editrequestbundle'),
        ),
    ]
