# Generated by Django 5.0 on 2024-01-27 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_alter_editsectionrequest_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmeetingrequest',
            name='end_time',
        ),
        migrations.AddField(
            model_name='editmeetingrequest',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=4500)),
            preserve_default=False,
        ),
    ]
